# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - studentscoreperformance

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://apptesting.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_ab3f8cc21fff4ab7b37c80bad7063384 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_261b33d69d6e44fb9a77fc16f66f134a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: apptesting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab3f8cc21fff4ab7b37c80bad7063384 }}/apptesting:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'studentscoreperformance'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_eeb04111d6c14251a53c3422d5c00ed5 }}
        images: 'apptesting.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_ab3f8cc21fff4ab7b37c80bad7063384 }}/apptesting:${{ github.sha }}'